DROP TABLE IF EXISTS Conference CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Paper CASCADE;
DROP TABLE IF EXISTS Topic CASCADE;
DROP TABLE IF EXISTS Expertise CASCADE;
DROP TABLE IF EXISTS Bid CASCADE;
DROP TABLE IF EXISTS Coi CASCADE;
DROP TABLE IF EXISTS Review CASCADE;
DROP TABLE IF EXISTS Submission CASCADE;
DROP TABLE IF EXISTS Author CASCADE;
DROP TABLE IF EXISTS PaperTopic CASCADE;
DROP TABLE IF EXISTS Members CASCADE;
DROP TABLE IF EXISTS ConferenceTopic CASCADE;

