DROP TABLE IF EXISTS conference CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS paper CASCADE;
DROP TABLE IF EXISTS topic CASCADE;
DROP TABLE IF EXISTS expertise CASCADE;
DROP TABLE IF EXISTS bid CASCADE;
DROP TABLE IF EXISTS coi CASCADE;
DROP TABLE IF EXISTS review CASCADE;
DROP TABLE IF EXISTS submission CASCADE;
DROP TABLE IF EXISTS author CASCADE;
DROP TABLE IF EXISTS PaperTopic CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS ConferenceTopic CASCADE;

